version: '3.8'

services:
  db:
    image: postgres:15
    container_name: trolley_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trolley_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: trolley_api
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/trolley_db
      SECRET_KEY: dev-secret-key-change-in-production
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: python -m flask run --host=0.0.0.0 --port=5000

volumes:
  postgres_data:
