"""Initial schema with all 8 tables

Revision ID: 8351523323ca
Revises: 
Create Date: 2025-10-26 03:04:56.352704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8351523323ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawer_code', sa.String(length=50), nullable=False),
    sa.Column('trolley_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('drawer_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawers_drawer_code'), ['drawer_code'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='employeestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)

    op.create_table('item_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'in_use', 'depleted', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_batches_batch_number'), ['batch_number'], unique=True)

    op.create_table('drawer_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layout_name', sa.String(length=100), nullable=False),
    sa.Column('drawer_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('designated_quantity', sa.Integer(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawer_id'], ['drawers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawer_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('empty', 'partial', 'full', 'needs_restock', name='drawerstatusenum'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawer_id'], ['drawers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restock_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('drawer_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('restock', 'removal', 'adjustment', name='actiontype'), nullable=False),
    sa.Column('quantity_changed', sa.Integer(), nullable=False),
    sa.Column('restock_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_time_seconds', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('efficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_warning_triggered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['item_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drawer_id'], ['drawers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawer_batch_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawer_status_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity_loaded', sa.Integer(), nullable=False),
    sa.Column('load_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_depleted', sa.Boolean(), nullable=False),
    sa.Column('depletion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['item_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drawer_status_id'], ['drawer_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawer_batch_tracking')
    op.drop_table('restock_history')
    op.drop_table('drawer_status')
    op.drop_table('drawer_layouts')
    with op.batch_alter_table('item_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_batches_batch_number'))

    op.drop_table('item_batches')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))

    op.drop_table('employees')
    with op.batch_alter_table('drawers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawers_drawer_code'))

    op.drop_table('drawers')
    # ### end Alembic commands ###
